version: 3

vars:

  NAME: ghcr.io/sciabarracom/openserverless-devcontainer

  TAG:
    sh: git tag --sort=-creatordate | head -n 1 || "latest"

tasks:

  show: "echo {{.NAME}}:{{.TAG}}"

  image-tag:
      - git tag -d "$(git tag)" || true
      - git tag "0.1.0-incubating.$(date +%y%m%d%H%M)"
      - task: show

  build:
      - docker build -t "{{.NAME}}:{{.TAG}}" . --load

  build-and-tag:
    - task: image-tag
    - task: build
